### ISSUE TITLE
Fit'n'finish checklist

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/react-chart-editor#290]
- [x] line colouring on fields for contour trace types
- [x] axis position field not hiding when axis is hidden
- [x] axis position field should be sensitive to which axis it is and show bot/top for x and left/right for y
- [x] default axis selector state for 3d 
- [x] exponents field not hidden when labels hidden
- [x] range slider fold not working
- [x] AxesFolds should autohide when empty
- [x] Layout panel in Axes missing 'anchor' field
- [x] step offset and step size should hide in Ticks when number of markers is custom
- [x] prefix/suffix fields should turn into text boxes when custom is selected
- [x] tickformat
- [x] missing flip vertical/horizontal controls in heatmap trace type
- [x] validate axes for ternary and pie
- [x] gaps in data selector appears the same for lines and gradients in contour
- [x] zmin/zmax don't hide when zauto is true
- [x] points color interferes with points colorscale and doesn't work with showscale
- [x] annotations: preconfigured annotation types
- [x] group style traces #160
- [x] empty menupanels shouldn't render a gear (i.e. tickprefixmode when no prefix present)
- [x] colorbar.tickfont.color not appearing, colorbar.tickprefix not disappearing
- [x] colorbar bgcolor doesn't work (or in workspace)
- [x] color picker at bottom of fold in panel in fold is clipped
- [x] `<br>` shouldn't show in rich text editor when empty (basically we should trim/strip the input)
- [x] hover projections/spikelines don't make sense on heatmaps (or aren't renderered)
- [x] step size on "fraction of plot" numerics should be 0.05 but sometimes they switch to pixel-mode due to another flag :( so we might need a compound control (e.g. in color-bar and shape and notes positioning)
- [x] clicking on checkbox label should select it
- [x] colorbars panel is empty for 3d scatter
- [x] what if there's 2 colorbars for one trace, like 3d scatters marker.color & line.color
- [x] mesh 3d: Contour on Hover, if option is at hide, all the contour details should now show (report plotly.js)
- [x] ensure that trace group names are localized
- [x] get proper default colors for symbol selector in multi-value context
- [x] remove exclusion of financial traces from grouped trace style tab
- [x] AxesSelector should select first non-All option by default
- [x] Shape default fill colour has alpha=0 ... odd to control opacity twice ... had to force defaults but it's weird to have to do this and for fill to appear on line shapes
- [x] Image defaults
- [x] https://github.com/plotly/react-plotly.js-editor/pull/357#discussion_r170995341
- [x] suplots UI more intuitive `overlaying` and `domain` setting
- [x] make sure it's no longer possible to wedge the figure by switching back and forth among secondary axes a bunch of times.
- [x] colorbar thickness, length should be smart sliders
- [x] numerics should use https://www.npmjs.com/package/react-click-n-hold for arrows
- [x] extra padding appears when empty Panels are rendered in colorbar folds
- [x] updatemenubutton controls appear when updatemenu is visible: hidden
- [x] panel menu items visibility: don't show panel menu items if they're not in useful in the plot the user is making
- [x] `side` in `StyleAxesPanel` is overloaded in tick labels for cartesian (bottom/top/left/right) and polar (direction CW/CCW) so both appear and it's weird.
- [x] `plot_bgcolor` only affects first plot?

**Comment by dmt0** [comment]
> zmin/zmax don't hide when zauto is true

From what I see in the [docs](https://plot.ly/javascript/reference/#contourcarpet-zauto), zmin/zmax do not depend on zauto

**Comment by nicolaskruchten** [comment]
Perhaps not for carpet plots but it looks like yes for heatmaps: https://plot.ly/javascript/reference/#heatmap-zauto

**Comment by nicolaskruchten** [comment]
Closing in favour of the million issues we just created... From now on: we see a bug = we create an issue.
